if (ANDROID)
	add_compile_options("-g")
	add_compile_options("-O2")
	add_compile_options("-faligned-new")
	add_compile_options("-ffast-math")
        add_compile_options("-Wno-format")
	add_compile_options("-Wno-parentheses")
        add_compile_options("-Wno-switch")
	add_compile_options("-Wno-tautological-undefined-compare")
	add_compile_options("-Wno-unused-value")
	add_compile_options("-Wno-writable-strings")
	add_compile_options("-Wno-invalid-offsetof")
	add_compile_options("-U__STRICT_ANSI__")
endif ()
