include(unpack)

set(GLM_HOME "${LIBS_DIRECTORY}/glm")
set(GLM_UNPACK_DIR ${CMAKE_BINARY_DIR})
set(GLM_BINARY_HOME ${GLM_UNPACK_DIR}/glm)
set(GLM_PACKAGE_NAME glm-0.9.9.3.7z)
set(GLM_PACKAGE "${GLM_HOME}/${GLM_PACKAGE_NAME}")
set(GLM_INCLUDE_DIR ${GLM_BINARY_HOME})
unpack(GLM ${GLM_PACKAGE} ${GLM_UNPACK_DIR})
